// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: file.proto

package file

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MyStreamingService_StreamData_FullMethodName = "/file.MyStreamingService/StreamData"
)

// MyStreamingServiceClient is the client API for MyStreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyStreamingServiceClient interface {
	StreamData(ctx context.Context, in *RequestBody, opts ...grpc.CallOption) (MyStreamingService_StreamDataClient, error)
}

type myStreamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMyStreamingServiceClient(cc grpc.ClientConnInterface) MyStreamingServiceClient {
	return &myStreamingServiceClient{cc}
}

func (c *myStreamingServiceClient) StreamData(ctx context.Context, in *RequestBody, opts ...grpc.CallOption) (MyStreamingService_StreamDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &MyStreamingService_ServiceDesc.Streams[0], MyStreamingService_StreamData_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &myStreamingServiceStreamDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MyStreamingService_StreamDataClient interface {
	Recv() (*ResponseBody, error)
	grpc.ClientStream
}

type myStreamingServiceStreamDataClient struct {
	grpc.ClientStream
}

func (x *myStreamingServiceStreamDataClient) Recv() (*ResponseBody, error) {
	m := new(ResponseBody)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MyStreamingServiceServer is the server API for MyStreamingService service.
// All implementations must embed UnimplementedMyStreamingServiceServer
// for forward compatibility
type MyStreamingServiceServer interface {
	StreamData(*RequestBody, MyStreamingService_StreamDataServer) error
	mustEmbedUnimplementedMyStreamingServiceServer()
}

// UnimplementedMyStreamingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMyStreamingServiceServer struct {
}

func (UnimplementedMyStreamingServiceServer) StreamData(*RequestBody, MyStreamingService_StreamDataServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamData not implemented")
}
func (UnimplementedMyStreamingServiceServer) mustEmbedUnimplementedMyStreamingServiceServer() {}

// UnsafeMyStreamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyStreamingServiceServer will
// result in compilation errors.
type UnsafeMyStreamingServiceServer interface {
	mustEmbedUnimplementedMyStreamingServiceServer()
}

func RegisterMyStreamingServiceServer(s grpc.ServiceRegistrar, srv MyStreamingServiceServer) {
	s.RegisterService(&MyStreamingService_ServiceDesc, srv)
}

func _MyStreamingService_StreamData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestBody)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MyStreamingServiceServer).StreamData(m, &myStreamingServiceStreamDataServer{stream})
}

type MyStreamingService_StreamDataServer interface {
	Send(*ResponseBody) error
	grpc.ServerStream
}

type myStreamingServiceStreamDataServer struct {
	grpc.ServerStream
}

func (x *myStreamingServiceStreamDataServer) Send(m *ResponseBody) error {
	return x.ServerStream.SendMsg(m)
}

// MyStreamingService_ServiceDesc is the grpc.ServiceDesc for MyStreamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyStreamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "file.MyStreamingService",
	HandlerType: (*MyStreamingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamData",
			Handler:       _MyStreamingService_StreamData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "file.proto",
}
